services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: fil
      POSTGRES_USER: fil
      POSTGRES_PASSWORD: fil
    ports:
      - "5432:5432"
    volumes:
      - fil_postgres:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - fil_redis:/data

volumes:
  fil_postgres:
  fil_redis:
